/*
  Warnings:

  - You are about to drop the column `annualExpenseEstimateExcludingPayrollRentDebtOwnersDrawFoodAndT` on the `InvestmentCommittee` table. All the data in the column will be lost.
  - You are about to drop the column `lesserOfAnnualRevenueFromBankaAndMPesaStatementsAnd75PercentCol` on the `InvestmentCommittee` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE "InvestmentCommittee" DROP COLUMN "annualExpenseEstimateExcludingPayrollRentDebtOwnersDrawFoodAndT",
DROP COLUMN "lesserOfAnnualRevenueFromBankaAndMPesaStatementsAnd75PercentCol",
ADD COLUMN     "annualExpenseEstimateExcludingPayrollRentDebtOwnersDrawFoodAndTransport" TEXT,
ADD COLUMN     "lesserOfAnnualRevenueFromBankaAndMPesaStatementsAnd75PercentCollections" TEXT;

-- CreateTable
CREATE TABLE "Loan" (
    "id" SERIAL NOT NULL,
    "sheetId" TEXT,
    "loanType" TEXT,
    "loanPurpose" TEXT,
    "borrowerType" TEXT,
    "borrowerId" TEXT,
    "borrowerName" TEXT,
    "principalAmount" TEXT,
    "interestType" TEXT,
    "annualDecliningInterest" TEXT,
    "annualFlatInterest" TEXT,
    "processingFeePercentage" TEXT,
    "creditLifeInsurancePercentage" TEXT,
    "securitizationFee" TEXT,
    "processingFee" TEXT,
    "creditLifeInsuranceFee" TEXT,
    "numberOfMonths" TEXT,
    "dailyPenalty" TEXT,
    "amountToDisburse" TEXT,
    "totalComprehensiveVehicleInsurancePaymentsToPay" TEXT,
    "totalInterestCharged" TEXT,
    "totalInterestToPay" TEXT,
    "totalPrincipalToPay" TEXT,
    "creditApplicationId" TEXT,
    "firstPaymentPeriod" TEXT,
    "createdBy" TEXT,
    "totalLiabilityAmountIncludingPenaltiesAndComprehensiveVehicleInsurance" TEXT,
    "totalLoanAmountPaidIncludingPenaltiesAndInsurance" TEXT,
    "totalPenaltiesAssessed" TEXT,
    "totalPenaltiesPaid" TEXT,
    "penaltiesStillDue" TEXT,
    "sslId" TEXT,
    "loanOverdue" TEXT,
    "par14" TEXT,
    "par30" TEXT,
    "par60" TEXT,
    "par90" TEXT,
    "par120" TEXT,
    "amountOverdue" TEXT,
    "loanFullyPaid" TEXT,
    "loanStatus" TEXT,
    "totalAmountDueToDate" TEXT,
    "amountDisbursedToDateIncludingFees" TEXT,
    "balanceOfDisbursementsOwed" TEXT,
    "principalPaidToDate" TEXT,
    "outstandingPrincipalBalance" TEXT,
    "numberOfAssetsUsedAsCollateral" TEXT,
    "numberOfAssetsRecorded" TEXT,
    "allCollateralRecorded" TEXT,
    "principalDifference" TEXT,
    "creditLifeInsuranceSubmitted" TEXT,
    "directorHasCompletedCreditLifeHealthExamination" TEXT,
    "recordOfReceiptForCreditLifeInsurance" TEXT,
    "percentDisbursed" TEXT,
    "daysLate" TEXT,
    "totalUnpaidLiability" TEXT,
    "restructured" TEXT,
    "collateralCheckedByLegalTeam" TEXT,
    "hasFemaleDirector" TEXT,
    "reportsGenerated" TEXT,
    "contractUploaded" TEXT,
    "percentChargeOnVehicleInsuranceFinancing" TEXT,
    "customerCareCallDone" TEXT,
    "checksHeld" TEXT,
    "remainingPeriodsForChecks" TEXT,
    "adequateChecksForRemainingPeriods" TEXT,
    "totalLiabilityAmountFromContract" TEXT,
    "liabilityCheck" TEXT,
    "creditLifeInsurer" TEXT,
    "interestChargedVsDueDifference" TEXT,
    "principalDueWithForgivenessVsWithoutForgiveness" TEXT,
    "insuranceDueWithVsWithoutForgiveness" TEXT,
    "firstLoan" TEXT,
    "additionalFeesWithheldFromDisbursement" TEXT,
    "daysSinceCreation" TEXT,
    "referral" TEXT,
    "numberOfInstallmentsOverdue" TEXT,
    "amountPaidTowardsOverdueInstallments" TEXT,
    "borrowerIdForContracts" TEXT,
    "mostRecentInstallmentPartiallyPaid" TEXT,
    "willingnessToPay" TEXT,
    "capabilityToPay" TEXT,
    "loanRiskCategory" TEXT,
    "calculatedAmountToDisburse" TEXT,
    "differenceBetweenCalculatedAndRecordedDisbursement" TEXT,
    "teachers" TEXT,
    "totalInterestPaid" TEXT,
    "outstandingInterestBalance" TEXT,
    "totalVehicleInsuranceDue" TEXT,
    "totalVehicleInsurancePaid" TEXT,
    "outstandingVehicleInsuranceBalance" TEXT,
    "reassigned" TEXT,
    "flexiLoan" TEXT,
    "loanQualifiesForCatalyzeProgram" TEXT,
    "allStaff" TEXT,
    "loanHasGonePAR30" TEXT,
    "hasMaleDirector" TEXT,
    "schoolArea" TEXT,
    "firstDisbursement" TEXT,
    "totalAdditionalFeesNotWithheldFromDisbursement" TEXT,
    "additionalFeesNotWithheldFromDisbursementPaid" TEXT,
    "additionalFeesNotWithheldFromDisbursementStillDue" TEXT,
    "averageSchoolFees" TEXT,
    "contractingDate" TEXT,
    "submittedToCatalyze" TEXT,
    "mostRecentContract" TEXT,
    "mostRecentContractType" TEXT,
    "schoolType" TEXT,
    "howManyClassroomsWillBeConstructedWithTheLoan" TEXT,
    "howManyVehiclesWillBePurchasedWithTheLoan" TEXT,
    "principalWrittenOff" TEXT,
    "interestWrittenOff" TEXT,
    "vehicleInsuranceWrittenOff" TEXT,
    "segmentedRepaymentView" TEXT,
    "beforeJan12024" TEXT,
    "loanNumber" TEXT,
    "teamLeader" TEXT,
    "vehicleInsuranceWithoutForgivenessCheck" TEXT,
    "vehicleInsuranceWithForgivenessCheck" TEXT,
    "suspendedInterestCharged" TEXT,
    "suspendedInterestDue" TEXT,
    "region" TEXT,
    "exciseDuty" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "synced" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "Loan_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Loan_sheetId_key" ON "Loan"("sheetId");
