-- CreateTable
CREATE TABLE "Borrower" (
    "id" SERIAL NOT NULL,
    "sheetId" TEXT,
    "customerType" TEXT,
    "type" TEXT,
    "name" TEXT,
    "locationDescription" TEXT,
    "societyCertificate" TEXT,
    "yearFounded" TEXT,
    "sslId" TEXT,
    "locationPin" TEXT,
    "historicalPaymentDetails" TEXT,
    "paymentMethod" TEXT,
    "bankName" TEXT,
    "accountName" TEXT,
    "accountNumber" TEXT,
    "primaryPhone" TEXT,
    "documentVerifyingAccount" TEXT,
    "managerVerification" TEXT,
    "status" TEXT,
    "notes" TEXT,
    "entityType" TEXT,
    "registrationNumber" TEXT,
    "notesOnStatus" TEXT,
    "officialSearch" TEXT,
    "pelezaSearch" TEXT,
    "productsRequested" TEXT,
    "dataCollectionProgress" DOUBLE PRECISION,
    "initialContactNotes" TEXT,
    "kraPinPhoto" TEXT,
    "kraPinNumber" TEXT,
    "createdAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "createdBy" TEXT,
    "howHeard" TEXT,
    "monthYearCreated" TEXT,
    "moeCertified" TEXT,
    "moeCertificate" TEXT,
    "county" TEXT,
    "cr12" TEXT,
    "nationalIdNumber" TEXT,
    "nationalIdFront" TEXT,
    "nationalIdBack" TEXT,
    "dateOfBirth" TIMESTAMP(3),
    "privateOrApbet" TEXT,
    "relatedCreditApplications" TEXT,
    "relatedHandoversGivingId" TEXT,
    "relatedHandoversReceivingId" TEXT,
    "relatedCrbConsents" TEXT,
    "relatedCollaterals" TEXT,
    "relatedUsers" TEXT,
    "relatedReferrers" TEXT,
    "relatedCustomerCareCalls" TEXT,
    "relatedEscalations" TEXT,
    "relatedEnrollmentReports" TEXT,
    "relatedLoans" TEXT,
    "relatedDirPaymentSchedules" TEXT,
    "relatedCollateralsByLoanId" TEXT,

    CONSTRAINT "Borrower_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Borrower_sheetId_key" ON "Borrower"("sheetId");
